config/routes.rb
SynctermIngles::Application.routes.draw do
  resources :iptables

  resources :timezones

  get "welcome/index"
  resources :timetables

  resources :appointments

  resources :sponsors

  resources :services

  resources :diaries

  resources :providers

  resources :receivers

  resources :administrators

  devise_for :users,
             :controllers => {:registrations => "my_devise/registrations"}

   root 'welcome#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
    has_one :user
    has_many :services
    has_many :diaries
    has_many :providers
    has_many :receivers
    has_and_belongs_to_many :appointments
    
    #Validations of the model.
    validates :user_id, :presence => true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :receiver
    belongs_to :diary
    has_and_belongs_to_many :administrators
end

app/models/diary.rb
class Diary < ActiveRecord::Base
	has_one :administrator
    has_many :appointments
    belongs_to :provider
    has_and_belongs_to_many :services
    has_and_belongs_to_many :timbetables
end

app/models/iptable.rb
class Iptable < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
    has_one :user
    has_many :diaries
    belongs_to :administrator

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
	has_one :user

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :administrator
	has_and_belongs_to_many :diaries
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
	has_one :user

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
end

app/models/timezone.rb
class Timezone < ActiveRecord::Base
	def name_and_area
		"#{coun_name} #{acronym} (+#{coun_area})"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:username]


  belongs_to :administrator
  belongs_to :receiver
  belongs_to :provider
  belongs_to :sponsor

  #Validations of the model.
  validates :username, 
            :name,
            :lastname,
            :phone_code,
            :phone,
            :email, :presence => true
  validates :terms_of_service, acceptance: true
  validates :username, :uniqueness => true
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  before_action :set_receiver, only: [:show, :edit, :update, :destroy]

  # GET /receivers
  # GET /receivers.json
  def index
    @receivers = Receiver.all
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
  end

  # GET /receivers/new
  def new
    @receiver = Receiver.new
  end

  # GET /receivers/1/edit
  def edit
  end

  # POST /receivers
  # POST /receivers.json
  def create
    @receiver = Receiver.new(receiver_params)

    respond_to do |format|
      if @receiver.save
        format.html { redirect_to @receiver, notice: 'Receiver was successfully created.' }
        format.json { render action: 'show', status: :created, location: @receiver }
      else
        format.html { render action: 'new' }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivers/1
  # PATCH/PUT /receivers/1.json
  def update
    respond_to do |format|
      if @receiver.update(receiver_params)
        format.html { redirect_to @receiver, notice: 'Receiver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    @receiver.destroy
    respond_to do |format|
      format.html { redirect_to receivers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receiver
      @receiver = Receiver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receiver_params
      params[:receiver]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/iptables_helper.rb
module IptablesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/timezones_helper.rb
module TimezonesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/receivers/_form.html.erb
<%= form_for(@receiver) do |f| %>
  <% if @receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% @receiver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receivers/edit.html.erb
<h1>Editing receiver</h1>

<%= render 'form' %>

<%= link_to 'Show', @receiver %> |
<%= link_to 'Back', receivers_path %>

app/views/receivers/index.html.erb
<h1>Listing receivers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @receivers.each do |receiver| %>
      <tr>
        <td><%= link_to 'Show', receiver %></td>
        <td><%= link_to 'Edit', edit_receiver_path(receiver) %></td>
        <td><%= link_to 'Destroy', receiver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receiver', new_receiver_path %>

app/views/receivers/new.html.erb
<h1>New receiver</h1>

<%= render 'form' %>

<%= link_to 'Back', receivers_path %>

app/views/receivers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_receiver_path(@receiver) %> |
<%= link_to 'Back', receivers_path %>