config/routes.rb
SynctermIngles::Application.routes.draw do
  resources :iptables

  resources :timezones

  get "welcome/index"
  resources :timetables

  resources :appointments

  resources :sponsors

  resources :services

  resources :diaries

  resources :providers

  resources :receivers

  resources :administrators

  devise_for :users,
             :controllers => {:registrations => "my_devise/registrations"}

   root 'welcome#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
    has_one :user
    has_many :services
    has_many :diaries
    has_many :providers
    has_many :receivers
    has_and_belongs_to_many :appointments
    
    #Validations of the model.
    validates :user_id, :presence => true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :receiver
    belongs_to :diary
    has_and_belongs_to_many :administrators
end

app/models/diary.rb
class Diary < ActiveRecord::Base
	has_one :administrator
    has_many :appointments
    belongs_to :provider
    has_and_belongs_to_many :services
    has_and_belongs_to_many :timbetables
end

app/models/iptable.rb
class Iptable < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
    has_one :user
    has_many :diaries
    belongs_to :administrator

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
	has_one :user

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :administrator
	has_and_belongs_to_many :diaries
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
	has_one :user

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
end

app/models/timezone.rb
class Timezone < ActiveRecord::Base
	def name_and_area
		"#{coun_name} #{acronym} (+#{coun_area})"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:username]


  belongs_to :administrator
  belongs_to :receiver
  belongs_to :provider
  belongs_to :sponsor

  #Validations of the model.
  validates :username, 
            :name,
            :lastname,
            :phone_code,
            :phone,
            :email, :presence => true
  validates :terms_of_service, acceptance: true
  validates :username, :uniqueness => true
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :set_timetable, only: [:show, :edit, :update, :destroy]

  # GET /timetables
  # GET /timetables.json
  def index
    @timetables = Timetable.all
  end

  # GET /timetables/1
  # GET /timetables/1.json
  def show
  end

  # GET /timetables/new
  def new
    @timetable = Timetable.new
  end

  # GET /timetables/1/edit
  def edit
  end

  # POST /timetables
  # POST /timetables.json
  def create
    @timetable = Timetable.new(timetable_params)

    respond_to do |format|
      if @timetable.save
        format.html { redirect_to @timetable, notice: 'Timetable was successfully created.' }
        format.json { render action: 'show', status: :created, location: @timetable }
      else
        format.html { render action: 'new' }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timetables/1
  # PATCH/PUT /timetables/1.json
  def update
    respond_to do |format|
      if @timetable.update(timetable_params)
        format.html { redirect_to @timetable, notice: 'Timetable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1
  # DELETE /timetables/1.json
  def destroy
    @timetable.destroy
    respond_to do |format|
      format.html { redirect_to timetables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timetable_params
      params[:timetable]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/iptables_helper.rb
module IptablesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/timezones_helper.rb
module TimezonesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/timetables/_form.html.erb
<%= form_for(@timetable) do |f| %>
  <% if @timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% @timetable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timetables/edit.html.erb
<h1>Editing timetable</h1>

<%= render 'form' %>

<%= link_to 'Show', @timetable %> |
<%= link_to 'Back', timetables_path %>

app/views/timetables/index.html.erb
<h1>Listing timetables</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @timetables.each do |timetable| %>
      <tr>
        <td><%= link_to 'Show', timetable %></td>
        <td><%= link_to 'Edit', edit_timetable_path(timetable) %></td>
        <td><%= link_to 'Destroy', timetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timetable', new_timetable_path %>

app/views/timetables/new.html.erb
<h1>New timetable</h1>

<%= render 'form' %>

<%= link_to 'Back', timetables_path %>

app/views/timetables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_timetable_path(@timetable) %> |
<%= link_to 'Back', timetables_path %>