config/routes.rb
SynctermIngles::Application.routes.draw do
  resources :iptables

  resources :timezones

  get "welcome/index"
  resources :timetables

  resources :appointments

  resources :sponsors

  resources :services

  resources :diaries

  resources :providers

  resources :receivers

  resources :administrators

  devise_for :users,
             :controllers => {:registrations => "my_devise/registrations"}

   root 'welcome#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
    has_one :user
    has_many :services
    has_many :diaries
    has_many :providers
    has_many :receivers
    has_and_belongs_to_many :appointments
    
    #Validations of the model.
    validates :user_id, :presence => true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :receiver
    belongs_to :diary
    has_and_belongs_to_many :administrators
end

app/models/diary.rb
class Diary < ActiveRecord::Base
	has_one :administrator
    has_many :appointments
    belongs_to :provider
    has_and_belongs_to_many :services
    has_and_belongs_to_many :timbetables
end

app/models/iptable.rb
class Iptable < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
    has_one :user
    has_many :diaries
    belongs_to :administrator

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
	has_one :user

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :administrator
	has_and_belongs_to_many :diaries
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
	has_one :user

	#Validations of the model.
	validates :user_id, :presence => true
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
end

app/models/timezone.rb
class Timezone < ActiveRecord::Base
	def name_and_area
		"#{coun_name} #{acronym} (+#{coun_area})"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:username]


  belongs_to :administrator
  belongs_to :receiver
  belongs_to :provider
  belongs_to :sponsor

  #Validations of the model.
  validates :username, 
            :name,
            :lastname,
            :phone_code,
            :phone,
            :email, :presence => true
  validates :terms_of_service, acceptance: true
  validates :username, :uniqueness => true
end

app/controllers/iptables_controller.rb
class IptablesController < ApplicationController
  before_action :set_iptable, only: [:show, :edit, :update, :destroy]

  # GET /iptables
  # GET /iptables.json
  def index
    @iptables = Iptable.all
  end

  # GET /iptables/1
  # GET /iptables/1.json
  def show
  end

  # GET /iptables/new
  def new
    @iptable = Iptable.new
  end

  # GET /iptables/1/edit
  def edit
  end

  # POST /iptables
  # POST /iptables.json
  def create
    @iptable = Iptable.new(iptable_params)

    respond_to do |format|
      if @iptable.save
        format.html { redirect_to @iptable, notice: 'Iptable was successfully created.' }
        format.json { render action: 'show', status: :created, location: @iptable }
      else
        format.html { render action: 'new' }
        format.json { render json: @iptable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iptables/1
  # PATCH/PUT /iptables/1.json
  def update
    respond_to do |format|
      if @iptable.update(iptable_params)
        format.html { redirect_to @iptable, notice: 'Iptable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @iptable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iptables/1
  # DELETE /iptables/1.json
  def destroy
    @iptable.destroy
    respond_to do |format|
      format.html { redirect_to iptables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iptable
      @iptable = Iptable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iptable_params
      params[:iptable]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/iptables_helper.rb
module IptablesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/timezones_helper.rb
module TimezonesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/iptables/_form.html.erb
<%= form_for(@iptable) do |f| %>
  <% if @iptable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iptable.errors.count, "error") %> prohibited this iptable from being saved:</h2>

      <ul>
      <% @iptable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/iptables/edit.html.erb
<h1>Editing iptable</h1>

<%= render 'form' %>

<%= link_to 'Show', @iptable %> |
<%= link_to 'Back', iptables_path %>

app/views/iptables/index.html.erb
<h1>Listing iptables</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @iptables.each do |iptable| %>
      <tr>
        <td><%= link_to 'Show', iptable %></td>
        <td><%= link_to 'Edit', edit_iptable_path(iptable) %></td>
        <td><%= link_to 'Destroy', iptable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iptable', new_iptable_path %>

app/views/iptables/new.html.erb
<h1>New iptable</h1>

<%= render 'form' %>

<%= link_to 'Back', iptables_path %>

app/views/iptables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_iptable_path(@iptable) %> |
<%= link_to 'Back', iptables_path %>